### PR TITLE
Pull featurability information from the spreadsheet in the format it's used.

### PR DESCRIPTION
**Pull request by leonardr**
The Reader Services spreadsheet uses 'x' in the column "Can be Featured on Catalog Page (Cat 1)" to indicate that a book may be featured in its primary category. A book that can't be featured has that column blank.

Currently we look in the column "Can be Featured on Catalog Page" (which doesn't exist) to check whether a book may be featured in its primary category. A book that can be featured may have any value other than 'N' or 'n' in that column.

Basically, we were allowing every single book to be featurable, since both 'x' and the empty string meant 'yes'. This branch makes our code treat "Can be Featured on Catalog Page (Cat 1)" the way Reader Services expects it to. Empty means 'no', 'n' or 'N' means 'no', and any other value means 'yes'.

Since we currently ignore the "MTA Category 2" field, I didn't add any special code for that, but if we do start respecting this field we'll need to make sure a book is only featurable in its primary category.

### CODE REVIEW

**Comment by nodanaonlyzuul** [comment]
Hey @leonardr .

If Reader Services expects...

> Empty means 'no', 'n' or 'N' means 'no', and any other value means 'yes'.

Than do you want to expand the conditional to be:

```python
if not featurable_value or featurable_value.strip().upper() == "N" or featurable_value.strip().upper() == "NO":
    featurable = False
```

Also - sorry to be thick but it looks like Reader Services is using "x" as a checkmark, an opting-into featurability - so, should we flip to being default NOT feautrable?

e.g:

```python
featurable_value = row.get(FEATURABLE_ON_CATALOG_PAGE)

featurable = False
if featurable_value and featurable_value.strip().upper() == "X":
    featurable = True
```

**Comment by leonardr** [comment]
Yeah, that's fine. The good thing about the code I originally wrote is that it handles both 'Y'/'N' and 'X'/'[empty string]', but since RS is actually using 'X'/'[empty string]' i don't think we need the extra complexity.

**Comment by nodanaonlyzuul** [comment]
Cool - I'm fine with what we have here...although I see that https://github.com/NYPL-Simplified/web-reader-landing-page/pull/136/commits/c66ba40c0a9a3cf84eda9fcc8c4e8529e37a50bb brought in a merge conflict. (oddly).

**Comment by nodanaonlyzuul** [comment]
Closing because this is handled by https://github.com/NYPL-Simplified/web-reader-landing-page/pull/142.

**Pull request closed without merging**
