### PR TITLE
Better nav

### PR DESCRIPTION
**Pull request by EdwinGuzman**
This fixes:
* #128 Removing the close button which had index = 2
* #75 adding back the browser's native focus state until we get a better one
* #103 Keeping the button in front of the sliding navigation menu - but **not** animating the icon

### CODE REVIEW

**Comment by aslagle** [comment]
Is it supposed to have a bottom outline like this?

screen shot 2017-05-04 at 2 53 01 pm

**Comment by aslagle** [comment]
About gets top and bottom outlines but the others only get bottom.

screen shot 2017-05-04 at 2 54 04 pm

**Comment by aslagle** [comment]
If you're tabbing through with the keyboard, you can't tell whether the one above or below the line has focus.

**Comment by EdwinGuzman** [comment]
That's the native browser's focus. There's another ticket to create a better outline. I just wanted to enable it to have something instead of nothing at all.

**Comment by EdwinGuzman** [comment]
@ricardoom reusing the same button for opening and closing the menu doesn't work as @wlla found out. When navigation up in the nav list, the "close" button get's skipped and the page focuses on the footer's privacy policy. I think reverting back to two icons and just overlapping will be best for now.

**Comment by EdwinGuzman** [comment]
PR updated and up on QA now.

**Comment by EdwinGuzman** [comment]
@wlla can you review this one more time before I merge this PR?

**Pull request merged**
